---

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#
# !!! WARNING !!!

# This option allows to control health check step
# Use this option with caution
health_check: true

# Perform force apt-get update
apt_update: false

# Action for customized packages which were installed not from
# specified repositories(uknown packages).
# Since it is useless to get diff for unknown package and
# somtimes it is impossible.
#
# Possible values:
# - "fail"      (default)
# - "keep"      (don't update these packages)
# - "reinstall" (update these packages, lost current packages)
# - any other mean "fail"
unknown_custom_pkgs: "fail"

# Action for upgradable packages which were installed not from
# specified repositories(unknown packages).
#
# Possible values:
# - "fail"      (default)
# - "keep"      (don't update these packages)
# - "reinstall" (update these packages, lost current packages)
# - any other mean "fail"
unknown_upgradable_pkgs: "fail"

# Perform force MD5 verification
md5_check: false

# Perform force gathering customizations
gather_customizations: false

