---

# !!! WARNING !!!
#
# Before modifiyng PLEASE read the documenation
# and make sure that you completly understand what
# means each step and how it impacts other steps
#

# This option allows to control health check step
# Use this option with caution
#
#health_check: false

# This option is used to control addition of defined
# temporary ceph_repo to existing apt config. You
# have to manually configure correct preference
# values for added repo if it uses custom package
# labeling scheme (i.e. Fuel doesn't configures
# preferences for packages in specified repo at all
# or doesn't do it correctly)
#
#add_ceph_repo: false

# Restart ceph services
restart_ceph: true
