---

- name: APT correct dependencies
  command: "apt-get -y -c {{ apt_conf }} -f install"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: APT upgrade
  command: "apt-get -y -c {{ apt_conf }} upgrade"
  environment:
    DEBIAN_FRONTEND: noninteractive

