---

- hosts: env_{{ env_id }}
  any_errors_fatal: true

  vars_files:
    - "vars/common.yml"

  tasks:

    - include: tasks/health_checks.yml
      when: health_check is undefined or
            health_check

